name: LNG  CNG  Asia
favicon: null
layout_spectrum: 0.5501777136232704
typography_spectrum: 0.6408100435510278
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.921506323851645
  lightness: 0.7046410802286118
  saturation: 0.8337437899317592
  rhythmicContrast: 0.5302826864644885
purpose: []
